# Generated by Django 5.0.7 on 2024-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_employees_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="profile_pic",
            field=models.ImageField(upload_to="profile_pics/"),
        ),
    ]
