# Generated by Django 5.0.7 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_employees_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="department",
            field=models.CharField(
                choices=[
                    ("CRM", "Customer Relationship Management"),
                    ("E&P", "Editorial and Publications"),
                    ("R&D", "Research and Development"),
                    ("S&D", "Software and Development"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Jr.Software Developer", "Junior Software Developer"),
                    ("Jr.Technical Writer", "Junior Technical Writer"),
                    ("BDE", "Business Development Executive"),
                    ("Research Associate", "Research Associate"),
                    ("Assistant Editor", "Assistant Editor"),
                    ("Client Relationship Associate", "Client Relationship Associate"),
                    ("Research Assistant", "Research Assistant"),
                    ("Executive Assistant", "Executive Assistant"),
                    ("Assistant Team Lead", "Assistant Team Lead"),
                    ("Team Lead", "Team Lead"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="father_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="employees",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="husband_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="employees",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Married", "Married"),
                    ("Unmarried", "Unmarried"),
                    ("Widow", "Widowed"),
                    ("Divorced", "Divorced"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
