# Generated by Django 5.0.7 on 2024-07-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_employees_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employees",
            old_name="city",
            new_name="state",
        ),
    ]
